// <auto-generated />
namespace Broadway.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class teachers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(teachers));
        
        string IMigrationMetadata.Id
        {
            get { return "202109210315277_teachers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
