//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broadway800AM.App.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OurEntities : DbContext
    {
        public OurEntities()
            : base("name=OurEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<student_backup> student_backup { get; set; }
        public virtual DbSet<studentparent> studentparents { get; set; }
        public virtual DbSet<tblnew> tblnews { get; set; }
        public virtual DbSet<parent> parents { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<vw_studentparentView> vw_studentparentView { get; set; }
        public virtual DbSet<tbl> tbls { get; set; }
    }
}
