//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Broadway800AM.App.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_studentparentView
    {
        public string studentname { get; set; }
        public string MotherName { get; set; }
        public string FatherName { get; set; }
    }
}
